# Spring properties
spring:
  application:
     name: orders-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/orders-server/templates/    # Trailing / mandatory
                             # Template location for this application only

#  datasource:
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
#    hikari.connection-test-query: values 1
#    hikari.maximum-pool-size: 25
#    jpa:
#      database-platform: DB2Platform
#      hibernate.ddl-auto: none
#      open-in-view: false
#      properties:
#        hibernate:
#          dll-auto: none
#          dialect: org.hibernate.dialect.DB2400Dialect
#          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

# Map the error path to error template (for Thymeleaf)
error.path: /error

# HTTP Server
server.port: 5555   # HTTP (Tomcat) port

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
eureka:
  client:
    serviceUrl:
      defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # DO NOT DO THIS IN PRODUCTION

#  3. If using the Angel release-train ONLY, give the process a unique instance id 
#     so that multiple instances can register when running on SAME host.  This is
#     not needed since release-train Brixton.
#     NOTE-1: spring.application.instance_id is only set when run on Cloud Foundry,
#             so we fallback on the server-port when it is not defined
#     NOTE-2: Syntax ${x:${y}} = use $x if set, otherwise use $y
#   metadataMap:
#     instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


# Enable actuator access without security checks - DEVELOPMENT ONLY
# Spring Boot 1.5
# management.security.enabled: false
# Spring Boot 2.x
management.endpoints.web.exposure.include: '*'

