# Ignore JDBC Dependency
# This demo puts 3 applicatons in the same project, so by default they all pick
# up the JDBC Depdendency, but this application doesn't need it.
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#okta:
#  oauth2:
#    issuer: https://{dev-47415479.okta.com}/oauth2/default
#    client-id: 0oa7sbl66YFgRokBt5d6
#    client-secret: e-l2_C_9yoW3G2m-X_pvHi882bSjoYY5YRjK3v_3

# Spring properties
spring:
  application:
    name: web-service  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/web-server/templates/    # Trailing / mandatory
                       # Template location for this application only
#
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: e012bb93de44306c0a30
#            client-secret: 7a70e689e365611cedec687d89424badb7a531b1
#          okta:
#            client-id: 0oa7sbl66YFgRokBt5d6
#            client-secret: e-l2_C_9yoW3G2m-X_pvHi882bSjoYY5YRjK3v_3
#            client-name: Okta
#        provider:
#          okta:
#            issuer-uri: https://{dev-47415479.okta.com}/oauth2/default
#
#    security:
#      oauth2:
#        resource:
#          prefer-token-info: true
#        client:
#          registration:
#            github:
#              client-id: e012bb93de44306c0a30
#              client-secret: 7a70e689e365611cedec687d89424badb7a531b1

# Map the error path to error template (for Thymeleaf)
error.path: /error

# HTTP Server
server.port: 3333   # HTTP (Tomcat) port

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
eureka:
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Enable actuator access without security checks - DEVELOPEMENT ONLY
# Spring Boot 1.5
# management.security.enabled: false
# Spring Boot 2.x
management.endpoints.web.exposure.include: '*'
  